name : mguhc
version : 1.2
main : fr.flobanai.mguhc.Main
api-version : 1.21.11
author : flobanai

commands:
  mg_setrole:
    description: Attribue un rôle à un joueur
    usage: /mg_setrole <joueur> <role>
  mg_getrole:
    description: Affiche le rôle d'un joueur
    usage: /mg_getrole [joueur]