name : mguhc
version : 1.2
main : fr.flobanai.mguhc.Main
api-version : 1.21.11
author : flobanai

commands:
  mg:
    description: Englobe l'entiéreté des commandes du plugin
    usage: /mg <subcommand> [parameters]
  
  #setrole:
    #description: Attribue un rôle à un joueur
    #usage: /mg setrole <joueur> <role>
  #getrole:
    #description: Affiche le rôle d'un joueur
    #usage: /mg getrole [joueur]